site_name: Minecraft Docs · John71
plugins: []

theme:
  name: readthedocs
  titles_only: True

nav:
  - index: index.md
  - Modpacks:
    - Crafting Eras: 'https://docs.minecraft.john71.eu/projects/Crafting-Eras/en/main/'
